const NV_OK = 0x00000000
const NV_ERR_GENERIC = 0x0000FFFF

const NV_ERR_BROKEN_FB = 0x00000001
const NV_ERR_BUFFER_TOO_SMALL = 0x00000002
const NV_ERR_BUSY_RETRY = 0x00000003
const NV_ERR_CALLBACK_NOT_SCHEDULED = 0x00000004
const NV_ERR_CARD_NOT_PRESENT = 0x00000005
const NV_ERR_CYCLE_DETECTED = 0x00000006
const NV_ERR_DMA_IN_USE = 0x00000007
const NV_ERR_DMA_MEM_NOT_LOCKED = 0x00000008
const NV_ERR_DMA_MEM_NOT_UNLOCKED = 0x00000009
const NV_ERR_DUAL_LINK_INUSE = 0x0000000A
const NV_ERR_ECC_ERROR = 0x0000000B
const NV_ERR_FIFO_BAD_ACCESS = 0x0000000C
const NV_ERR_FREQ_NOT_SUPPORTED = 0x0000000D
const NV_ERR_GPU_DMA_NOT_INITIALIZED = 0x0000000E
const NV_ERR_GPU_IS_LOST = 0x0000000F
const NV_ERR_GPU_IN_FULLCHIP_RESET = 0x00000010
const NV_ERR_GPU_NOT_FULL_POWER = 0x00000011
const NV_ERR_GPU_UUID_NOT_FOUND = 0x00000012
const NV_ERR_HOT_SWITCH = 0x00000013
const NV_ERR_I2C_ERROR = 0x00000014
const NV_ERR_I2C_SPEED_TOO_HIGH = 0x00000015
const NV_ERR_ILLEGAL_ACTION = 0x00000016
const NV_ERR_IN_USE = 0x00000017
const NV_ERR_INFLATE_COMPRESSED_DATA_FAILED = 0x00000018
const NV_ERR_INSERT_DUPLICATE_NAME = 0x00000019
const NV_ERR_INSUFFICIENT_RESOURCES = 0x0000001A
const NV_ERR_INSUFFICIENT_PERMISSIONS = 0x0000001B
const NV_ERR_INSUFFICIENT_POWER = 0x0000001C
const NV_ERR_INVALID_ACCESS_TYPE = 0x0000001D
const NV_ERR_INVALID_ADDRESS = 0x0000001E
const NV_ERR_INVALID_ARGUMENT = 0x0000001F
const NV_ERR_INVALID_BASE = 0x00000020
const NV_ERR_INVALID_CHANNEL = 0x00000021
const NV_ERR_INVALID_CLASS = 0x00000022
const NV_ERR_INVALID_CLIENT = 0x00000023
const NV_ERR_INVALID_COMMAND = 0x00000024
const NV_ERR_INVALID_DATA = 0x00000025
const NV_ERR_INVALID_DEVICE = 0x00000026
const NV_ERR_INVALID_DMA_SPECIFIER = 0x00000027
const NV_ERR_INVALID_EVENT = 0x00000028
const NV_ERR_INVALID_FLAGS = 0x00000029
const NV_ERR_INVALID_FUNCTION = 0x0000002A
const NV_ERR_INVALID_HEAP = 0x0000002B
const NV_ERR_INVALID_INDEX = 0x0000002C
const NV_ERR_INVALID_IRQ_LEVEL = 0x0000002D
const NV_ERR_INVALID_LIMIT = 0x0000002E
const NV_ERR_INVALID_LOCK_STATE = 0x0000002F
const NV_ERR_INVALID_METHOD = 0x00000030
const NV_ERR_INVALID_OBJECT = 0x00000031
const NV_ERR_INVALID_OBJECT_BUFFER = 0x00000032
const NV_ERR_INVALID_OBJECT_HANDLE = 0x00000033
const NV_ERR_INVALID_OBJECT_NEW = 0x00000034
const NV_ERR_INVALID_OBJECT_OLD = 0x00000035
const NV_ERR_INVALID_OBJECT_PARENT = 0x00000036
const NV_ERR_INVALID_OFFSET = 0x00000037
const NV_ERR_INVALID_OPERATION = 0x00000038
const NV_ERR_INVALID_OWNER = 0x00000039
const NV_ERR_INVALID_PARAM_STRUCT = 0x0000003A
const NV_ERR_INVALID_PARAMETER = 0x0000003B
const NV_ERR_INVALID_PATH = 0x0000003C
const NV_ERR_INVALID_POINTER = 0x0000003D
const NV_ERR_INVALID_REGISTRY_KEY = 0x0000003E
const NV_ERR_INVALID_REQUEST = 0x0000003F
const NV_ERR_INVALID_STATE = 0x00000040
const NV_ERR_INVALID_STRING_LENGTH = 0x00000041
const NV_ERR_INVALID_READ = 0x00000042
const NV_ERR_INVALID_WRITE = 0x00000043
const NV_ERR_INVALID_XLATE = 0x00000044
const NV_ERR_IRQ_NOT_FIRING = 0x00000045
const NV_ERR_IRQ_EDGE_TRIGGERED = 0x00000046
const NV_ERR_MEMORY_TRAINING_FAILED = 0x00000047
const NV_ERR_MISMATCHED_SLAVE = 0x00000048
const NV_ERR_MISMATCHED_TARGET = 0x00000049
const NV_ERR_MISSING_TABLE_ENTRY = 0x0000004A
const NV_ERR_MODULE_LOAD_FAILED = 0x0000004B
const NV_ERR_MORE_DATA_AVAILABLE = 0x0000004C
const NV_ERR_MORE_PROCESSING_REQUIRED = 0x0000004D
const NV_ERR_MULTIPLE_MEMORY_TYPES = 0x0000004E
const NV_ERR_NO_FREE_FIFOS = 0x0000004F
const NV_ERR_NO_INTR_PENDING = 0x00000050
const NV_ERR_NO_MEMORY = 0x00000051
const NV_ERR_NO_SUCH_DOMAIN = 0x00000052
const NV_ERR_NO_VALID_PATH = 0x00000053
const NV_ERR_NOT_COMPATIBLE = 0x00000054
const NV_ERR_NOT_READY = 0x00000055
const NV_ERR_NOT_SUPPORTED = 0x00000056
const NV_ERR_OBJECT_NOT_FOUND = 0x00000057
const NV_ERR_OBJECT_TYPE_MISMATCH = 0x00000058
const NV_ERR_OPERATING_SYSTEM = 0x00000059
const NV_ERR_OTHER_DEVICE_FOUND = 0x0000005A
const NV_ERR_OUT_OF_RANGE = 0x0000005B
const NV_ERR_OVERLAPPING_UVM_COMMIT = 0x0000005C
const NV_ERR_PAGE_TABLE_NOT_AVAIL = 0x0000005D
const NV_ERR_PID_NOT_FOUND = 0x0000005E
const NV_ERR_PROTECTION_FAULT = 0x0000005F
const NV_ERR_RC_ERROR = 0x00000060
const NV_ERR_REJECTED_VBIOS = 0x00000061
const NV_ERR_RESET_REQUIRED = 0x00000062
const NV_ERR_STATE_IN_USE = 0x00000063
const NV_ERR_SIGNAL_PENDING = 0x00000064
const NV_ERR_TIMEOUT = 0x00000065
const NV_ERR_TIMEOUT_RETRY = 0x00000066
const NV_ERR_TOO_MANY_PRIMARIES = 0x00000067
const NV_ERR_UVM_ADDRESS_IN_USE = 0x00000068
const NV_ERR_MAX_SESSION_LIMIT_REACHED = 0x00000069
const NV_ERR_LIB_RM_VERSION_MISMATCH = 0x0000006A
const NV_ERR_PRIV_SEC_VIOLATION = 0x0000006B
const NV_ERR_GPU_IN_DEBUG_MODE = 0x0000006C
const NV_ERR_FEATURE_NOT_ENABLED = 0x0000006D
const NV_ERR_RESOURCE_LOST = 0x0000006E
const NV_ERR_PMU_NOT_READY = 0x0000006F
const NV_ERR_FLCN_ERROR = 0x00000070
const NV_ERR_FATAL_ERROR = 0x00000071
const NV_ERR_MEMORY_ERROR = 0x00000072
const NV_ERR_INVALID_LICENSE = 0x00000073
const NV_ERR_NVLINK_INIT_ERROR = 0x00000074
const NV_ERR_NVLINK_MINION_ERROR = 0x00000075
const NV_ERR_NVLINK_CLOCK_ERROR = 0x00000076
const NV_ERR_NVLINK_TRAINING_ERROR = 0x00000077
const NV_ERR_NVLINK_CONFIGURATION_ERROR = 0x00000078
const NV_ERR_RISCV_ERROR = 0x00000079

const NV_WARN_HOT_SWITCH = 0x00010001
const NV_WARN_INCORRECT_PERFMON_DATA = 0x00010002
const NV_WARN_MISMATCHED_SLAVE = 0x00010003
const NV_WARN_MISMATCHED_TARGET = 0x00010004
const NV_WARN_MORE_PROCESSING_REQUIRED = 0x00010005
const NV_WARN_NOTHING_TO_DO = 0x00010006
const NV_WARN_NULL_OBJECT = 0x00010007
const NV_WARN_OUT_OF_RANGE = 0x00010008

const ERR_CODES = Dict(
    NV_OK =>  "Success",
    NV_ERR_GENERIC =>  "Failure: Generic Error",

    NV_ERR_BROKEN_FB =>  "Frame-Buffer broken",
    NV_ERR_BUFFER_TOO_SMALL =>  "Buffer passed in is too small",
    NV_ERR_BUSY_RETRY =>  "System is busy, retry later",
    NV_ERR_CALLBACK_NOT_SCHEDULED =>  "The requested callback API not scheduled",
    NV_ERR_CARD_NOT_PRESENT =>  "Card not detected",
    NV_ERR_CYCLE_DETECTED =>  "Call cycle detected",
    NV_ERR_DMA_IN_USE =>  "Requested DMA is in use",
    NV_ERR_DMA_MEM_NOT_LOCKED =>  "Requested DMA memory is not locked",
    NV_ERR_DMA_MEM_NOT_UNLOCKED =>  "Requested DMA memory is not unlocked",
    NV_ERR_DUAL_LINK_INUSE =>  "Dual-Link is in use",
    NV_ERR_ECC_ERROR =>  "Generic ECC error",
    NV_ERR_FIFO_BAD_ACCESS =>  "FIFO: Invalid access",
    NV_ERR_FREQ_NOT_SUPPORTED =>  "Requested frequency is not supported",
    NV_ERR_GPU_DMA_NOT_INITIALIZED =>  "Requested DMA not initialized",
    NV_ERR_GPU_IS_LOST =>  "GPU lost from the bus",
    NV_ERR_GPU_IN_FULLCHIP_RESET =>  "GPU currently in full-chip reset",
    NV_ERR_GPU_NOT_FULL_POWER =>  "GPU not in full power",
    NV_ERR_GPU_UUID_NOT_FOUND =>  "GPU UUID not found",
    NV_ERR_HOT_SWITCH =>  "System in hot switch",
    NV_ERR_I2C_ERROR =>  "I2C Error",
    NV_ERR_I2C_SPEED_TOO_HIGH =>  "I2C Error: Speed too high",
    NV_ERR_ILLEGAL_ACTION =>  "Current action is not allowed",
    NV_ERR_IN_USE =>  "Generic busy error",
    NV_ERR_INFLATE_COMPRESSED_DATA_FAILED =>  "Failed to inflate compressed data",
    NV_ERR_INSERT_DUPLICATE_NAME =>  "Found a duplicate entry in the requested btree",
    NV_ERR_INSUFFICIENT_RESOURCES =>  "Ran out of a critical resource, other than memory",
    NV_ERR_INSUFFICIENT_PERMISSIONS =>  "The requester does not have sufficient permissions",
    NV_ERR_INSUFFICIENT_POWER =>  "Generic Error: Low power",
    NV_ERR_INVALID_ACCESS_TYPE =>  "This type of access is not allowed",
    NV_ERR_INVALID_ADDRESS =>  "Address not valid",
    NV_ERR_INVALID_ARGUMENT =>  "Invalid argument to call",
    NV_ERR_INVALID_BASE =>  "Invalid base",
    NV_ERR_INVALID_CHANNEL =>  "Given channel-id not valid",
    NV_ERR_INVALID_CLASS =>  "Given class-id not valid",
    NV_ERR_INVALID_CLIENT =>  "Given client not valid",
    NV_ERR_INVALID_COMMAND =>  "Command passed is not valid",
    NV_ERR_INVALID_DATA =>  "Invalid data passed",
    NV_ERR_INVALID_DEVICE =>  "Current device is not valid",
    NV_ERR_INVALID_DMA_SPECIFIER =>  "The requested DMA specifier is not valid",
    NV_ERR_INVALID_EVENT =>  "Invalid event occurred",
    NV_ERR_INVALID_FLAGS =>  "Invalid flags passed",
    NV_ERR_INVALID_FUNCTION =>  "Called function is not valid",
    NV_ERR_INVALID_HEAP =>  "Heap corrupted",
    NV_ERR_INVALID_INDEX =>  "Index invalid",
    NV_ERR_INVALID_IRQ_LEVEL =>  "Requested IRQ level is not valid",
    NV_ERR_INVALID_LIMIT =>  "Generic Error: Invalid limit",
    NV_ERR_INVALID_LOCK_STATE =>  "Requested lock state not valid",
    NV_ERR_INVALID_METHOD =>  "Requested method not valid",
    NV_ERR_INVALID_OBJECT =>  "Object not valid",
    NV_ERR_INVALID_OBJECT_BUFFER =>  "Object buffer passed is not valid",
    NV_ERR_INVALID_OBJECT_HANDLE =>  "Object handle is not valid",
    NV_ERR_INVALID_OBJECT_NEW =>  "New object is not valid",
    NV_ERR_INVALID_OBJECT_OLD =>  "Old object is not valid",
    NV_ERR_INVALID_OBJECT_PARENT =>  "Object parent is not valid",
    NV_ERR_INVALID_OFFSET =>  "The offset passed is not valid",
    NV_ERR_INVALID_OPERATION =>  "Requested operation is not valid",
    NV_ERR_INVALID_OWNER =>  "Owner not valid",
    NV_ERR_INVALID_PARAM_STRUCT =>  "Invalid structure parameter",
    NV_ERR_INVALID_PARAMETER =>  "At least one of the parameters passed is not valid",
    NV_ERR_INVALID_PATH =>  "The requested path is not valid",
    NV_ERR_INVALID_POINTER =>  "Pointer not valid",
    NV_ERR_INVALID_REGISTRY_KEY =>  "Found an invalid registry key",
    NV_ERR_INVALID_REQUEST =>  "Generic Error: Invalid request",
    NV_ERR_INVALID_STATE =>  "Generic Error: Invalid state",
    NV_ERR_INVALID_STRING_LENGTH =>  "The string length is not valid",
    NV_ERR_INVALID_READ =>  "The requested read operation is not valid",
    NV_ERR_INVALID_WRITE =>  "The requested write operation is not valid",
    NV_ERR_INVALID_XLATE =>  "The requested translate operation is not valid",
    NV_ERR_IRQ_NOT_FIRING =>  "Requested IRQ is not firing",
    NV_ERR_IRQ_EDGE_TRIGGERED =>  "IRQ is edge triggered",
    NV_ERR_MEMORY_TRAINING_FAILED =>  "Failed memory training sequence",
    NV_ERR_MISMATCHED_SLAVE =>  "Slave mismatch",
    NV_ERR_MISMATCHED_TARGET =>  "Target mismatch",
    NV_ERR_MISSING_TABLE_ENTRY =>  "Requested entry missing not found in the table",
    NV_ERR_MODULE_LOAD_FAILED =>  "Failed to load the requested module",
    NV_ERR_MORE_DATA_AVAILABLE =>  "There is more data available",
    NV_ERR_MORE_PROCESSING_REQUIRED =>  "More processing required for the given call",
    NV_ERR_MULTIPLE_MEMORY_TYPES =>  "Multiple memory types found",
    NV_ERR_NO_FREE_FIFOS =>  "No more free FIFOs found",
    NV_ERR_NO_INTR_PENDING =>  "No interrupt pending",
    NV_ERR_NO_MEMORY =>  "Out of memory",
    NV_ERR_NO_SUCH_DOMAIN =>  "Requested domain does not exist",
    NV_ERR_NO_VALID_PATH =>  "Caller did not specify a valid path",
    NV_ERR_NOT_COMPATIBLE =>  "Generic Error: Incompatible types",
    NV_ERR_NOT_READY =>  "Generic Error: Not ready",
    NV_ERR_NOT_SUPPORTED =>  "Call not supported",
    NV_ERR_OBJECT_NOT_FOUND =>  "Requested object not found",
    NV_ERR_OBJECT_TYPE_MISMATCH =>  "Specified objects do not match",
    NV_ERR_OPERATING_SYSTEM =>  "Generic operating system error",
    NV_ERR_OTHER_DEVICE_FOUND =>  "Found other device instead of the requested one",
    NV_ERR_OUT_OF_RANGE =>  "The specified value is out of bounds",
    NV_ERR_OVERLAPPING_UVM_COMMIT =>  "Overlapping unified virtual memory commit",
    NV_ERR_PAGE_TABLE_NOT_AVAIL =>  "Requested page table not available",
    NV_ERR_PID_NOT_FOUND =>  "Process-Id not found",
    NV_ERR_PROTECTION_FAULT =>  "Protection fault",
    NV_ERR_RC_ERROR =>  "Generic RC error",
    NV_ERR_REJECTED_VBIOS =>  "Given Video BIOS rejected/invalid",
    NV_ERR_RESET_REQUIRED =>  "Reset required",
    NV_ERR_STATE_IN_USE =>  "State in use",
    NV_ERR_SIGNAL_PENDING =>  "Signal pending",
    NV_ERR_TIMEOUT =>  "Call timed out",
    NV_ERR_TIMEOUT_RETRY =>  "Call timed out, please retry later",
    NV_ERR_TOO_MANY_PRIMARIES =>  "Too many primaries",
    NV_ERR_UVM_ADDRESS_IN_USE =>  "Unified virtual memory requested address already in use",
    NV_ERR_MAX_SESSION_LIMIT_REACHED =>  "Maximum number of sessions reached",
    NV_ERR_LIB_RM_VERSION_MISMATCH =>  "Library version doesn't match driver version",
    NV_ERR_PRIV_SEC_VIOLATION =>  "Priv security violation",
    NV_ERR_GPU_IN_DEBUG_MODE =>  "GPU currently in debug mode",
    NV_ERR_FEATURE_NOT_ENABLED =>  "Requested Feature functionality is not enabled",
    NV_ERR_RESOURCE_LOST =>  "Requested resource has been destroyed",
    NV_ERR_PMU_NOT_READY =>  "PMU is not ready or has not yet been initialized",
    NV_ERR_FLCN_ERROR =>  "Generic falcon assert or halt",
    NV_ERR_FATAL_ERROR =>  "Fatal/unrecoverable error",
    NV_ERR_MEMORY_ERROR =>  "Generic memory error",
    NV_ERR_INVALID_LICENSE =>  "License provided is rejected or invalid",
    NV_ERR_NVLINK_INIT_ERROR =>  "Nvlink Init Error",
    NV_ERR_NVLINK_MINION_ERROR =>  "Nvlink Minion Error",
    NV_ERR_NVLINK_CLOCK_ERROR =>  "Nvlink Clock Error",
    NV_ERR_NVLINK_TRAINING_ERROR =>  "Nvlink Training Error",
    NV_ERR_NVLINK_CONFIGURATION_ERROR =>  "Nvlink Configuration Error",
    NV_ERR_RISCV_ERROR =>  "Generic RISC-V assert or halt",

    # Warnings:
    NV_WARN_HOT_SWITCH =>  "WARNING Hot switch",
    NV_WARN_INCORRECT_PERFMON_DATA =>  "WARNING Incorrect performance monitor data",
    NV_WARN_MISMATCHED_SLAVE =>  "WARNING Slave mismatch",
    NV_WARN_MISMATCHED_TARGET =>  "WARNING Target mismatch",
    NV_WARN_MORE_PROCESSING_REQUIRED =>  "WARNING More processing required for the call",
    NV_WARN_NOTHING_TO_DO =>  "WARNING Nothing to do",
    NV_WARN_NULL_OBJECT =>  "WARNING NULL object found",
    NV_WARN_OUT_OF_RANGE =>  "WARNING value out of range",
)

macro nvcheck(err)
    quote
        if $(esc(err)) != $NV_OK
            error($ERR_CODES[$(esc(err))])
        end
    end
end